In [2]:
import torch


<module 'torch.version' from '/usr/local/lib/python3.12/dist-packages/torch/version.py'>


In [5]:
print(torch.__version__)


2.11.0+cpu


In [9]:
if torch.cuda.is_available():
    print("Gpu is available")
    print(f"Using Gpu (torch.cuda.get_device_name(0))")
else:
  print("GPU not available,using CPU")

GPU not available,using CPU


ARTHMETIC OPERATIONS

In [3]:
import torch

# Scalar (0D)
a = torch.tensor(5)

# Vector (1D)
b = torch.tensor([1, 2, 3])

# Matrix (2D)
c = torch.tensor([[1, 2],
                  [3, 4]])

In [6]:
x = torch.empty(2, 3)
print(x.shape)
x = torch.empty(2, 2, dtype=torch.int32)
print(x)
type(x)


torch.Size([2, 3])
tensor([[1191611792,      31784],
        [1191611792,      31784]], dtype=torch.int32)


torch.Tensor

In [ ]:
torch.empty()# fills the tensor with garbage values already in the system
torch.zeros() #erases the whiteboard and writes 0 everywhere.
torch.ones() #writes 1 everywhere.
torch.empty() #just hands you the whiteboard without erasing it.
torch.rand()#random

In [7]:
import torch

x = torch.rand(2, 3)#distributed between 0 and 1.

print(x)

tensor([[0.4047, 0.9090, 0.5145],
        [0.9413, 0.9984, 0.0259]])


In [8]:
torch.manual_seed(42)

print(torch.rand(3))#running again same result

tensor([0.8823, 0.9150, 0.3829])


In [9]:
x = torch.tensor([1, 2, 3, 4])

print(x)

tensor([1, 2, 3, 4])


In [10]:
# other ways

# arange ,torch.arange(start, end, step)
print("using arange ->", torch.arange(0,10,2))#tensor([0, 2, 4, 6, 8]) 10  is excluded
torch.arange(1, 6)#tensor([1, 2, 3, 4, 5])
# using linspace
print("using linspace ->", torch.linspace(0,10,10))#here no.of steps instead of stepvalue
torch.linspace(1, 5, 5)
# using eye
print("using eye ->", torch.eye(5))#creates diagonal matrixes

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


In [ ]:
x = torch.full((3, 3), 5)#torch.full(size, fill_value)

print(x)

TENSOR SHAPES

In [11]:
x = torch.tensor([[1,2,3],[4,5,6]])
x
x.shape

torch.Size([2, 3])

In [12]:
torch.empty_like(x)

tensor([[7309453675965983778, 8315168162784306286, 8367752027310484831],
        [7954801838398993778, 2459029315949324647, 3762256541822366306]])

In [13]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [14]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [15]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])