In [4]:
import torch


In [5]:
print(torch.__version__)


2.11.0+cpu


In [6]:
if torch.cuda.is_available():
    print("Gpu is available")
    print(f"Using Gpu (torch.cuda.get_device_name(0))")
else:
  print("GPU not available,using CPU")

GPU not available,using CPU


ARTHMETIC OPERATIONS

In [7]:
import torch

# Scalar (0D)
a = torch.tensor(5)

# Vector (1D)
b = torch.tensor([1, 2, 3])

# Matrix (2D)
c = torch.tensor([[1, 2],
                  [3, 4]])

In [8]:
x = torch.empty(2, 3)
print(x.shape)
x = torch.empty(2, 2, dtype=torch.int32)
print(x)
type(x)


torch.Size([2, 3])
tensor([[-619281936,      32021],
        [-619281936,      32021]], dtype=torch.int32)


torch.Tensor

In [9]:
torch.empty()# fills the tensor with garbage values already in the system
torch.zeros() #erases the whiteboard and writes 0 everywhere.
torch.ones() #writes 1 everywhere.
torch.empty() #just hands you the whiteboard without erasing it.
torch.rand()#random

TypeError: empty() received an invalid combination of arguments - got (), but expected one of:
 * (tuple of ints size, *, tuple of names names, torch.memory_format memory_format = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)
 * (tuple of ints size, *, torch.memory_format memory_format = None, Tensor out = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)


In [11]:
import torch

x = torch.rand(2, 3)#distributed between 0 and 1.

print(x)

tensor([[0.5183, 0.4143, 0.5455],
        [0.6846, 0.8107, 0.9785]])


In [12]:
torch.manual_seed(42)

print(torch.rand(3))#running again same result

tensor([0.8823, 0.9150, 0.3829])


In [13]:
x = torch.tensor([1, 2, 3, 4])

print(x)

tensor([1, 2, 3, 4])


In [14]:
# other ways

# arange ,torch.arange(start, end, step)
print("using arange ->", torch.arange(0,10,2))#tensor([0, 2, 4, 6, 8]) 10  is excluded
torch.arange(1, 6)#tensor([1, 2, 3, 4, 5])
# using linspace
print("using linspace ->", torch.linspace(0,10,10))#here no.of steps instead of stepvalue
torch.linspace(1, 5, 5)
# using eye
print("using eye ->", torch.eye(5))#creates diagonal matrixes

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


In [15]:
x = torch.full((3, 3), 5)#torch.full(size, fill_value)

print(x)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


TENSOR SHAPES

In [16]:
x = torch.tensor([[1,2,3],[4,5,6]])
x
x.shape

torch.Size([2, 3])

In [17]:
torch.empty_like(x)#uninitialized tensor with the same shape

tensor([[0, 0, 0],
        [0, 0, 0]])

In [18]:
torch.zeros_like(x)#creates tensor same shapeas x

tensor([[0, 0, 0],
        [0, 0, 0]])

In [19]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [20]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])

TENSOR DATA TYPES

In [21]:
x.dtype

torch.int64

In [22]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [23]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [24]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

MATHEMATICAL OPERATIONS

SCALAR OPERATIONS

In [25]:
x = torch.rand(2,2)
x

tensor([[0.1332, 0.9346],
        [0.5936, 0.8694]])

In [26]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.0177, 0.8735],
        [0.3523, 0.7559]])

ELEMENTWISE OPERATIONS

In [27]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666]])
tensor([[0.6274, 0.2696, 0.4414],
        [0.2969, 0.8317, 0.1053]])


In [28]:
#torch.matmul(a, b) this is tthe mtrix muktiplication

In [29]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.5677, 0.2018, 0.4294],
        [0.2916, 0.5739, 0.0560]])

In [30]:
a = torch.tensor([1, 2, 3])

a.add_(2)#the tensor is modified

print(a)

tensor([3, 4, 5])


In [31]:
c = torch.tensor([1, -2, 3, -4])


In [32]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [33]:
torch.neg(c)

tensor([-1,  2, -3,  4])

In [34]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])


In [35]:
torch.round(d)
torch.ceil(d)
torch.floor(d)

tensor([1., 2., 3., 4.])

In [36]:
torch.clamp(d, min=2, max=3)#"Make every value in tensor d stay between 2 and 3."

tensor([2.0000, 2.3000, 3.0000, 3.0000])

REDUCTION OPERATIONS

Reduction operations reduce multiple values in a tensor into one value (or one value per row/column).

In [37]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)#creates a tensor with values low and high
e

tensor([[3., 1., 9.],
        [7., 9., 2.]])

In [38]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([13., 18.])

In [40]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)
# median
torch.median(e)
# max and min
torch.max(e)
torch.min(e)

tensor(1.)

In [42]:
# Product of all elements.
torch.prod(e)

tensor(3402.)

In [41]:

# standard deviation
torch.std(e)
# variance
torch.var(e)
# argmax
torch.argmax(e)
# argmin
torch.argmin(e)

tensor(1)

MATRIX OPERATIONS

In [43]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[0, 5, 9],
        [3, 4, 9]])
tensor([[6, 2],
        [0, 6],
        [2, 7]])


In [44]:
torch.matmul(f, g)

tensor([[18, 93],
        [36, 93]])

In [45]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [47]:
# transpose
torch.transpose(f, 0, 1)

tensor([[0, 3],
        [5, 4],
        [9, 9]])

In [53]:
x = torch.arange(6)

print(x.reshape(2,3))



tensor([[0, 1, 2],
        [3, 4, 5]])


In [49]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[0., 9., 6.],
        [9., 5., 4.],
        [8., 8., 6.]])

In [50]:
# determinant
torch.det(h)

tensor(-6.0000)

In [51]:
# determinant
torch.inverse(h)

tensor([[  0.3333,   1.0000,  -1.0000],
        [  3.6667,   8.0000,  -9.0000],
        [ -5.3333, -12.0000,  13.5000]])

COMPARISOM OPERATIONS

In [56]:
i=torch.randint(size=(2,3),low=0,high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[3, 8, 9],
        [3, 7, 8]])
tensor([[1, 4, 1],
        [6, 3, 2]])


In [57]:
# greater than
i > j
# less than
i < j


tensor([[False, False, False],
        [ True, False, False]])

In [58]:
# equal to
i == j
# not equal to
i != j
# greater than equal to
i >= j
# less than equal to
i <= j

tensor([[False, False, False],
        [ True, False, False]])

**Special** **functions**

In [59]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[0., 9., 8.],
        [5., 3., 7.]])

In [60]:
# log
torch.log(k)

tensor([[  -inf, 2.1972, 2.0794],
        [1.6094, 1.0986, 1.9459]])

In [61]:
# exp
torch.exp(k)

tensor([[1.0000e+00, 8.1031e+03, 2.9810e+03],
        [1.4841e+02, 2.0086e+01, 1.0966e+03]])

In [62]:
# sqrt
torch.sqrt(k)

tensor([[0.0000, 3.0000, 2.8284],
        [2.2361, 1.7321, 2.6458]])

In [63]:
# sigmoid
torch.sigmoid(k)

tensor([[0.5000, 0.9999, 0.9997],
        [0.9933, 0.9526, 0.9991]])

In [64]:
# softmax,0 < sigmoid(x) < 1
torch.softmax(k, dim=0)

tensor([[0.0067, 0.9975, 0.7311],
        [0.9933, 0.0025, 0.2689]])

In [66]:
# relu
torch.relu(k)

tensor([[0., 9., 8.],
        [5., 3., 7.]])

INPLACE OPERATIONS

In [67]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.3725, 0.7980, 0.8399],
        [0.1374, 0.2331, 0.9578]])
tensor([[0.3313, 0.3227, 0.0162],
        [0.2137, 0.6249, 0.4340]])


In [68]:
m.add_(n)

tensor([[0.7038, 1.1208, 0.8561],
        [0.3511, 0.8580, 1.3918]])

In [70]:
n,m

(tensor([[0.3313, 0.3227, 0.0162],
         [0.2137, 0.6249, 0.4340]]),
 tensor([[0.7038, 1.1208, 0.8561],
         [0.3511, 0.8580, 1.3918]]))

In [71]:
m.relu_()

tensor([[0.7038, 1.1208, 0.8561],
        [0.3511, 0.8580, 1.3918]])

In [72]:
m

tensor([[0.7038, 1.1208, 0.8561],
        [0.3511, 0.8580, 1.3918]])

In [ ]:
import torch

# Model outputs (logits)
logits = torch.tensor([-2.0, -0.5, 0.0, 1.2, 3.0])

# Apply sigmoid
probabilities = torch.sigmoid(logits)

print("Probabilities:")
print(probabilities)

# Convert probabilities to True/False using a threshold of 0.5
predictions = probabilities >= 0.5

print("\nPredictions:")
print(predictions)

COPYING TENSORS

In [73]:
a = torch.rand(2,3)
a

tensor([[0.1371, 0.5117, 0.1585],
        [0.0758, 0.2247, 0.0624]])

In [74]:
b=a

In [75]:
a[0][0]=0

In [76]:
a

tensor([[0.0000, 0.5117, 0.1585],
        [0.0758, 0.2247, 0.0624]])

In [77]:
b#the value of b changes too

tensor([[0.0000, 0.5117, 0.1585],
        [0.0758, 0.2247, 0.0624]])

In [78]:
id(a)

137532177985568

In [79]:
id(b)

137532177985568

In [80]:
b=a.clone()

In [82]:
a[0][0]=10

In [83]:
a

tensor([[10.0000,  0.5117,  0.1585],
        [ 0.0758,  0.2247,  0.0624]])

In [84]:
b

tensor([[0.0000, 0.5117, 0.1585],
        [0.0758, 0.2247, 0.0624]])

In [85]:
id(a)

137532177985568

In [86]:
id(b)

137531396782464

Tensor Operations

In [87]:
torch.cuda.is_available()

False

In [88]:
device=torch.device("cuda")